services:
  server:
    build: .
    ports:
      - '2127:2127'
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - CONNECTION_POOL_MIN_SIZE=${CONNECTION_POOL_MIN_SIZE}
      - CONNECTION_POOL_MAX_SIZE=${CONNECTION_POOL_MAX_SIZE}
